{% set version = "5.12.1" %}
{% set pscom_version = "5.9.1" %}

package:
  name: psmpi
  version: {{ version }}

source:
  - url: https://github.com/ParaStation/psmpi/archive/refs/tags/{{ version }}-2.tar.gz
    sha256: 1989a1e13770c23db08d8e5e3fddee798bd782716f3aa86a34b52e9c6a220bbe
    folder: psmpi
  - url: https://github.com/ParaStation/pscom/archive/refs/tags/{{ pscom_version }}-1.tar.gz
    sha256: 8fed647151e64072ca8b6903a5101529562783ec81aa0e60fcc59fd08444d454
    folder: pscom
    patches:
      - fix-headers.patch 
      - fix-pscom-macros.patch

build:
  number: 3
  run_exports:
    - {{ pin_subpackage('psmpi', max_pin='x.y.z') }}
  skip: true  # [win or osx or aarch64]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - autoconf
    - automake
    - cmake
    - libtool
    - make
    - pkg-config
  host:
    - libhwloc
    - libpmix-devel
    - prrte
    - ucx
  run:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - libhwloc
    - libpmix
    - prrte
    - ucx

test:
  files:
    - hello_world_mpi.f90
  commands:
    - mpichversion
    - mpifort -o hello_world_mpi hello_world_mpi.f90
    - test -f $PREFIX/lib/libmpi.so

about:
  home: https://github.com/ParaStation/psmpi
  license: QPL-1.0
  license_family: OTHER
  license_file: LICENSE
  summary: ParaStation MPI is an MPIch based implementation of the Message-Passing Interface (MPI) Standard.
  description: |
    ParaStation MPI relies on a low-level communication layer called `pscom` and provides full MPI-4 compliance. 
    
    Since it is configured with the Process Management Interface for Exascale (PMIx), an external job launcher is 
    required to run MPI jobs. Typically, in high-performance computing environments using the Slurm Workload Manager,
    applications would be executed with:

    ```
    srun --mpi=pmix mpi_application
    ```

extra:
  recipe-maintainers:
    - j34ni
