{% set psmpi_version = "4.3.2" %}
{% set shs_libfabric_version = "2.2.0" %}

package:
  name: psmpi-shs
  version: {{ psmpi_version }}

source:
  - url: https://github.com/ParaStation/psmpi/archive/refs/tags/vendor-{{ psmpi_version }}.tar.gz
    sha256: 52ce34df369622f283a6f54e2b70675f5b4870d64b54d0e96c3e6eb0818b7b35
    folder: psmpi
  - url: https://github.com/HewlettPackard/shs-libfabric/archive/refs/tags/v{{ shs_libfabric_version }}.tar.gz
    sha256: 734aa46fc1a5c69c59514aade3e8f17037506fbb08013f4be63d669e546570b0
    folder: shs-libfabric
    patches:
      - fix_reallocarray.patch 
      - define_map_huge_shift.patch 

build:
  number: 0
  string: shs_h{{ PKG_HASH }}
  skip: true  # [win or osx]
  run_exports:
    - {{ pin_subpackage('psmpi-shs', max_pin='x.y.z') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - autoconf
    - automake
    - libtool
    - make
  host:
    - libhwloc
    - libpmix-devel
    - prrte
    - ucx
    - json-c
    - libcurl
    - libnl
    - rdma-core
    - shs-cassini-headers
    - shs-libcxi
    - shs-cxi-drivers
  run:
    - libhwloc
    - prrte
    - ucx
    - json-c
    - libcurl
    - libnl
    - rdma-core
    - shs-libcxi

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  files:
    - hello_world_mpi.f90 
  commands:
    - test -f $PREFIX/lib/libmpi.so
    - test -f $PREFIX/bin/mpicc
    - test -f $PREFIX/bin/mpifort
    - test -f $PREFIX/bin/mpiexec || test -f $PREFIX/bin/prterun 
    - mpifort -o hello_world_mpi hello_world_mpi.f90
    - prterun --map-by :HWTCPUS:OVERSUBSCRIBE -np 2 ./hello_world_mpi || mpiexec -n 2 ./hello_world_mpi

about:
  home: https://github.com/ParaStation/psmpi
  license: Custom (MPICH permissive license)
  license_family: Other
  license_file:
    - psmpi/mpich2/COPYRIGHT
    - shs-libfabric/COPYING 
  summary: ParaStation MPI (vendor branch 4.3.2) with Slingshot support via shs-libfabric
  description: |
    This package builds the vendor-4.3.2 branch of ParaStation MPI (MPICH-based) with the CH4 device 
    configured for dual UCX + OFI support. It bundles a Slingshot-optimized libfabric (shs-libfabric) 
    for HPE Cray Slingshot interconnects (CXI provider).

    To force the OFI netmod: `export MPICH_CH4_NETMOD=ofi` (or `ucx` for UCX).
    For Slingshot, use `FI_PROVIDER=cxi`.

        Since it is configured with the Process Management Interface for Exascale (PMIx), an external job launcher
    is required to run MPI jobs spawning multiple nodes, typically in a high-performance computing environment.

    For instance using the Slurm Workload Manager, applications would be executed with:

    ```
    srun --mpi=pmix mpi_application
    ```

    For single-node jobs (here with 2 processes) use instead `prterun` :

    ```
    prterun -np 2 ./mpi_application"
    ```

extra:
  recipe-maintainers:
    - j34ni
